-- ==================================================
-- Part 1: S1.3, S3.1, S3.2 (26 câu)
-- 26 câu hỏi
-- ==================================================

INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0151', 'S1.3', 2, 'single_choice', 'Theo Quy chế 756/QĐ-BYT, khoa Phẫu thuật-Gây mê hồi sức trực thuộc:', '["Khoa Ngoại", "Khối Ngoại - hệ thống KCB của bệnh viện", "Khoa Hồi sức cấp cứu", "Đứng độc lập"]'::jsonb, 1, 'QC 756 quy định khoa PTGMHS thuộc khối Ngoại, là khoa lâm sàng hỗ trợ cho các khoa ngoại.', '', ARRAY['VB08'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0152', 'S1.3', 1, 'single_choice', 'Trưởng khoa PTGMHS phải đạt trình độ:', '["ĐD Đại học", "BS Chuyên khoa I trở lên hoặc tương đương về Gây mê hồi sức", "Y sĩ", "Không yêu cầu cụ thể"]'::jsonb, 1, 'Trưởng khoa PTGMHS phải là BS có chứng chỉ Chuyên khoa GMHS theo QC 756.', '', ARRAY['VB08'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0153', 'S1.3', 2, 'single_choice', 'Phòng mổ phải đảm bảo điều kiện vô khuẩn theo quy định nào của BYT?', '["QĐ 3916", "TT 18/2009", "TT 35/2014", "Tất cả đáp án trên"]'::jsonb, 3, 'Phòng mổ chịu nhiều quy định: QĐ 3916 về KSNK, TT 18/2009 về tổ chức khoa PTGMHS, TT 35/2014 về điều kiện cơ sở.', '', ARRAY['VB08','VB09'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0154', 'S1.3', 1, 'single_choice', 'Phòng hồi tỉnh (PACU) thuộc trách nhiệm của:', '["Khoa Ngoại", "Khoa PTGMHS", "Khoa Hồi sức tích cực", "Tất cả"]'::jsonb, 1, 'Phòng hồi tỉnh là một bộ phận của khoa PTGMHS theo QC 756.', '', ARRAY['VB08'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0155', 'S1.3', 2, 'single_choice', 'ĐD GMHS trực 24/24 phải có ít nhất:', '["1 người", "2 người (1 trong phòng mổ, 1 hồi tỉnh)", "3 người", "Tuỳ ca mổ"]'::jsonb, 1, 'Quy định trực bệnh viện hạng 1: ít nhất 2 ĐD trực ca - 1 phụ mổ và 1 chăm sóc hồi tỉnh.', '', ARRAY['VB08'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0156', 'S1.3', 2, 'single_choice', 'Ai có quyền quyết định hoãn ca mổ vì lý do gây mê?', '["BS gây mê chính", "Phẫu thuật viên chính", "Trưởng khoa PTGMHS", "Cả BS gây mê và PTV"]'::jsonb, 3, 'BS gây mê và PTV cùng đánh giá; nếu một trong hai không an toàn → hoãn. Trưởng khoa PTGMHS có thẩm quyền cuối.', '', ARRAY['VB08'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0157', 'S1.3', 1, 'single_choice', 'Ai chịu trách nhiệm chính về an toàn của NB trong giai đoạn gây mê?', '["Phẫu thuật viên", "BS gây mê", "ĐD gây mê", "Tất cả kíp mổ"]'::jsonb, 1, 'BS gây mê chịu trách nhiệm chính về an toàn gây mê - quy định rõ trong QC 756.', '', ARRAY['VB08'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0158', 'S1.3', 2, 'single_choice', 'Hồ sơ gây mê hồi sức cần lưu trong bao lâu (tối thiểu)?', '["1 năm", "5 năm", "10 năm theo quy định hồ sơ bệnh án", "15 năm"]'::jsonb, 2, 'Theo TT 50/2017 và quy chế hồ sơ bệnh án BYT: ≥ 10 năm với hồ sơ điều trị nội trú có can thiệp.', '', ARRAY['VB08'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0159', 'S3.1', 1, 'single_choice', 'Phương pháp định nhóm máu ABO trên giấy dùng để:', '["Test nhanh trước truyền máu", "Test trong tình huống cấp cứu khi không có labo", "Test tham khảo, không thay thế labo", "Tất cả các đáp án trên đều đúng"]'::jsonb, 3, 'Test trên giấy là quick test, dùng cấp cứu/tham khảo, vẫn cần XN labo để xác nhận trước truyền máu thực tế.', '*', ARRAY['KT01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0160', 'S3.1', 2, 'single_choice', 'Khi định nhóm ABO trên giấy, máu NB và huyết thanh mẫu trộn theo tỷ lệ?', '["1:1", "1:2", "Theo hướng dẫn cụ thể của nhà SX (thường 1 giọt máu : 1 giọt anti-)", "Tỷ lệ tự do"]'::jsonb, 2, 'Theo hướng dẫn nhà SX, thường 1 giọt máu BN trộn với 1 giọt huyết thanh kháng (anti-A, anti-B, anti-AB).', '*', ARRAY['KT01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0161', 'S3.1', 2, 'single_choice', 'Sau khi trộn máu với huyết thanh mẫu, đọc kết quả trong bao lâu?', '["Ngay lập tức", "Sau 30 giây - 2 phút (theo hướng dẫn)", "Sau 5-10 phút", "Sau 30 phút"]'::jsonb, 1, 'Đọc ngưng kết trong khoảng thời gian quy định, thường 30s-2 phút. Đọc quá sớm/muộn có thể sai.', '*', ARRAY['KT01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0162', 'S3.1', 3, 'single_choice', 'Ngưng kết yếu hoặc không rõ ràng có thể do nguyên nhân nào?', '["Huyết thanh mẫu hết hạn", "Nhiệt độ phòng quá thấp/cao", "Mẫu hồng cầu loãng quá", "Tất cả các đáp án"]'::jsonb, 3, 'Các yếu tố này đều ảnh hưởng. Cần lặp lại test với mẫu tươi, huyết thanh mới, nhiệt độ phòng chuẩn.', '*', ARRAY['KT01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0163', 'S3.1', 2, 'single_choice', 'Hồng cầu chứng A1, B trong bộ test ABO dùng để:', '["Kiểm tra hoạt lực huyết thanh mẫu", "Đối chứng với huyết thanh BN (phát hiện kháng thể)", "Cả 2 đáp án trên", "Không cần thiết"]'::jsonb, 2, 'HC chứng A1, B dùng để định kiểu huyết thanh - phát hiện kháng thể tự nhiên trong huyết thanh BN.', '*', ARRAY['KT01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0164', 'S3.1', 3, 'single_choice', 'Trên giấy định nhóm: máu NB ngưng kết với anti-AB và anti-A, không ngưng kết với anti-B. HC chứng A1 không ngưng kết với huyết thanh NB. Kết quả nhóm máu?', '["Nhóm A", "Nhóm B", "Nhóm AB", "Nhóm O"]'::jsonb, 0, 'Kiểu hồng cầu: A+, B-, AB+ → nhóm A. HC A1 không ngưng kết với HT BN xác nhận BN nhóm A (không có anti-A).', '*', ARRAY['KT01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0165', 'S3.1', 2, 'single_choice', 'Khi định nhóm máu, đọc kết quả nghi ngờ (ngưng kết yếu), bước tiếp theo là:', '["Bỏ qua, dùng đại", "Báo BS, lặp lại test với mẫu mới, gửi labo xác nhận", "Tự quyết định", "Hỏi đồng nghiệp"]'::jsonb, 1, 'Kết quả nghi ngờ luôn phải xác minh - không tự ý kết luận khi không chắc chắn.', '*', ARRAY['KT01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0166', 'S3.1', 1, 'single_choice', 'Trước khi định nhóm máu, ĐD cần kiểm tra:', '["Tên BN trên ống máu", "Mã định danh BN", "Hạn dùng + nhiệt độ bảo quản huyết thanh mẫu", "Tất cả các đáp án"]'::jsonb, 3, 'Cần kiểm tra đối chiếu BN (5 đúng) + chất lượng huyết thanh mẫu trước khi test.', '*', ARRAY['KT01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0167', 'S3.1', 2, 'single_choice', 'ĐD trình độ Cao đẳng làm việc trong khoa GMHS thực hiện được kỹ thuật định nhóm máu trên giấy như thế nào?', '["Không bao giờ", "Chỉ phụ giúp dưới sự giám sát của ĐD ĐH+ hoặc BS - không xác nhận ''Làm đúng'' độc lập", "Tự thực hiện như TT", "Hoàn toàn tự chịu trách nhiệm"]'::jsonb, 1, 'Kỹ thuật (*) chuyên khoa - ĐD CĐ chỉ phụ giúp, kết quả phải có ĐD ĐH+ hoặc BS xác nhận.', '*', ARRAY['KT01','VB01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0168', 'S3.1', 3, 'single_choice', 'Trường hợp hồng cầu BN ngưng kết với cả anti-A, anti-B, anti-AB nhưng HT BN cũng ngưng kết với HC chứng cả A1 và B. Diễn giải kết quả?', '["Nhóm AB", "Cần lặp lại test - kết quả mâu thuẫn, có thể do bệnh lý hoặc lỗi kỹ thuật", "Nhóm O", "Hồng cầu cảm ứng tự miễn"]'::jsonb, 1, 'Kết quả mâu thuẫn (BN có cả kháng nguyên A,B trên HC nhưng cũng có kháng thể anti-A, anti-B trong huyết thanh) → phải lặp lại + labo xác minh.', '*', ARRAY['KT01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0169', 'S3.2', 1, 'single_choice', 'Định nhóm máu cho chế phẩm tiểu cầu khác so với khối hồng cầu vì:', '["Cùng quy trình", "Tiểu cầu không có kháng nguyên ABO", "Tiểu cầu có ít kháng nguyên ABO + cần ưu tiên match nhóm HLA", "Không cần định nhóm tiểu cầu"]'::jsonb, 2, 'Tiểu cầu có kháng nguyên ABO yếu hơn HC, nhưng quan trọng nhất là match HLA để giảm phản ứng đa miễn dịch.', '*', ARRAY['KT02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0170', 'S3.2', 2, 'single_choice', 'Định nhóm máu trên huyết tương đông lạnh tươi (FFP) khác KHC vì:', '["FFP chứa kháng thể, không phải kháng nguyên - định kiểu kháng thể", "Cùng quy trình", "FFP không cần định nhóm", "FFP không có kháng nguyên/kháng thể"]'::jsonb, 0, 'FFP có nhiều kháng thể tự nhiên (anti-A, anti-B). Định nhóm FFP là xác định kháng thể, ngược với HC.', '*', ARRAY['KT02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0171', 'S3.2', 2, 'single_choice', 'Truyền FFP cho NB nhóm O, đơn vị FFP an toàn nhất là:', '["FFP nhóm O (chứa anti-A và anti-B)", "FFP nhóm AB (universal donor cho FFP)", "FFP nhóm A", "FFP nhóm B"]'::jsonb, 1, 'FFP nhóm AB không chứa anti-A, anti-B → an toàn cho mọi NB nhóm. Ngược với HC (O là universal cho HC).', '*', ARRAY['KT02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0172', 'S3.2', 1, 'single_choice', 'Cryoprecipitate (tủa lạnh) chứa chủ yếu:', '["Tiểu cầu", "Yếu tố VIII, fibrinogen, vWF, yếu tố XIII", "Hồng cầu", "Bạch cầu"]'::jsonb, 1, 'Cryo chứa các yếu tố đông máu chủ yếu - dùng trong rối loạn đông máu, fibrinogen thấp, hemophilia A.', '*', ARRAY['KT02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0173', 'S3.2', 2, 'single_choice', 'Truyền tủa lạnh có cần định nhóm máu ABO không?', '["Có, cần khớp ABO", "Khuyến cáo match ABO nhưng không bắt buộc khi cấp cứu", "Không bao giờ cần", "Tuỳ ý"]'::jsonb, 1, 'Cryo có ít kháng thể, có thể truyền không match ABO trong cấp cứu, nhưng khuyến cáo match khi có thể.', '*', ARRAY['KT02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0174', 'S3.2', 3, 'single_choice', 'NB nam 45 tuổi, nhóm O, cần truyền cấp cứu 6 đơn vị FFP. Kho máu chỉ còn FFP nhóm A. Xử trí?', '["Truyền ngay vì cấp cứu", "Hội chẩn BS huyết học - rủi ro tan máu cao với FFP A truyền cho NB O", "Pha loãng FFP", "Từ chối truyền"]'::jsonb, 1, 'FFP nhóm A có anti-B; truyền cho NB O cần cân nhắc kỹ. Cần hội chẩn BS huyết học.', '*', ARRAY['KT02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0175', 'S3.2', 2, 'single_choice', 'Theo TT32, kỹ thuật định nhóm máu trên huyết tương/tiểu cầu/tủa được phân loại?', '["Cấp cứu (+)", "Chuyên khoa (*)", "Cơ bản (không dấu)", "Không xác định"]'::jsonb, 1, 'Phụ lục 12 TT32 phân loại định nhóm máu các chế phẩm là kỹ thuật chuyên khoa (*).', '*', ARRAY['KT02','VB02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0176', 'S3.2', 1, 'single_choice', 'Bảo quản FFP đông lạnh phải ở nhiệt độ:', '["2-8°C", "-18°C", "-25°C trở xuống", "Nhiệt độ phòng"]'::jsonb, 2, 'FFP cần bảo quản ≤ -25°C để giữ hoạt lực các yếu tố đông máu, đặc biệt yếu tố V và VIII.', '*', ARRAY['KT02'], 'approved') ON CONFLICT (id) DO NOTHING;

-- ==================================================
-- Part 2: S3.5, S3.6, S3.7, S3.8, S4.4, S5.3, S6.3
-- 60 câu hỏi mới (Q0177-Q0236)
-- ==================================================

INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0177', 'S3.5', 1, 'single_choice', 'Vai trò chính của ĐD dụng cụ (scrub nurse) là:', '["Chuẩn bị + đưa dụng cụ vô khuẩn cho PTV", "Theo dõi sinh hiệu", "Ghi chép biên bản", "Quản lý hành chính"]'::jsonb, 0, 'ĐD dụng cụ phục vụ trực tiếp PTV trong vùng vô khuẩn: chuẩn bị, sắp xếp, đưa dụng cụ.', '', ARRAY['KT05'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0178', 'S3.5', 1, 'single_choice', 'Vai trò chính của ĐD chạy ngoài (circulating nurse) là:', '["Phục vụ kíp mổ ngoài vùng vô khuẩn (cung ứng vật tư, ghi chép, liên lạc)", "Đưa dụng cụ trực tiếp", "Phẫu thuật", "Gây mê"]'::jsonb, 0, 'ĐD chạy ngoài hỗ trợ kíp mổ từ bên ngoài vùng vô khuẩn: lấy dụng cụ thêm, ghi chép, liên lạc khoa khác.', '', ARRAY['KT05'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0179', 'S3.5', 2, 'single_choice', 'Khi đếm dụng cụ trước mổ, nếu thiếu 1 dụng cụ, xử trí?', '["Bỏ qua, dụng cụ đó không quan trọng", "Báo PTV ngay + tìm hoặc thay thế trước khi rạch da", "Tự ý hoãn ca mổ", "Để sau ca mổ kiểm tra"]'::jsonb, 1, 'Báo PTV ngay - mọi sai sót về dụng cụ phải được giải quyết trước rạch da.', '', ARRAY['KT05'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0180', 'S3.5', 2, 'single_choice', 'Khi ĐD dụng cụ chạm tay vô khuẩn vào vùng không vô khuẩn, xử trí?', '["Lau cồn", "Coi như đã nhiễm - thay găng vô khuẩn", "Bỏ qua nếu không thấy bẩn", "Báo cáo sau"]'::jsonb, 1, 'Vô khuẩn không thoả hiệp - chạm vùng không vô khuẩn = nhiễm → phải thay găng.', '', ARRAY['KT05'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0181', 'S3.5', 3, 'single_choice', 'Trong quá trình mổ, ĐD dụng cụ cần đếm dụng cụ ở những thời điểm nào?', '["Chỉ trước rạch da", "Trước rạch da + trước đóng khoang + sau khi đóng da", "Chỉ cuối ca", "Bất kỳ lúc nào PTV yêu cầu"]'::jsonb, 1, '3 thời điểm bắt buộc: trước rạch da, trước đóng khoang, sau đóng da.', '', ARRAY['KT05','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0182', 'S3.5', 2, 'single_choice', 'Khi ĐD chạy ngoài cần lấy thêm dụng cụ từ tủ vô khuẩn, đưa cho ĐD dụng cụ:', '["Trực tiếp đưa từ tay sang tay", "Mở gói vô khuẩn + thả vào bàn vô khuẩn (không chạm)", "Dùng găng vô khuẩn để chuyển", "Ném vào bàn"]'::jsonb, 1, 'Kỹ thuật đưa dụng cụ vô khuẩn từ ngoài: mở gói + thả gentle vào bàn vô khuẩn, không chạm vùng vô khuẩn.', '', ARRAY['KT05'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0183', 'S3.5', 1, 'single_choice', 'Bộ kíp mổ tối thiểu gồm:', '["1 PTV, 1 ĐD", "1 PTV chính + 1 phụ + 1 ĐD dụng cụ + 1 ĐD chạy ngoài + BS GM + ĐD GM", "2 PTV", "Không quy định"]'::jsonb, 1, 'Kíp mổ chuẩn cho ca trung bình - lớn cần đầy đủ các vai trò trên.', '', ARRAY['KT05'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0184', 'S3.5', 2, 'single_choice', 'Đối tượng phụ trách bảo quản bệnh phẩm sau mổ (gửi giải phẫu bệnh):', '["BS gây mê", "ĐD dụng cụ + ĐD chạy ngoài (gắn nhãn + làm phiếu)", "Lao công", "NB tự bảo quản"]'::jsonb, 1, 'ĐD chịu trách nhiệm bảo quản, gắn nhãn (tên BN, mã, loại bệnh phẩm), làm phiếu gửi GPB.', '', ARRAY['KT05'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0185', 'S3.6', 1, 'single_choice', 'Trước khi sắp xếp dụng cụ trên bàn vô khuẩn, ĐD phải kiểm tra:', '["Số lượng dụng cụ", "Tình trạng vô khuẩn (bao bì còn nguyên, hạn dùng, chỉ thị màu)", "Sự phù hợp với loại phẫu thuật", "Tất cả các đáp án"]'::jsonb, 3, 'Kiểm tra đầy đủ: số lượng theo bộ, vô khuẩn (bao bì nguyên, indicator đổi màu, còn hạn), phù hợp loại mổ.', '', ARRAY['KT06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0186', 'S3.6', 2, 'single_choice', 'Dụng cụ sau khi sử dụng trong mổ được xử lý theo thứ tự:', '["Bỏ trực tiếp vào sọt rác", "Rửa nước thường rồi tiệt khuẩn", "Tráng - ngâm dung dịch khử nhiễm - rửa sạch - kiểm tra - đóng gói - tiệt khuẩn", "Bảo quản nguyên trạng để dùng tiếp"]'::jsonb, 2, 'Quy trình chuẩn xử lý dụng cụ tái sử dụng (decontamination cycle).', '', ARRAY['KT06','VB09'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0187', 'S3.6', 2, 'single_choice', 'Chỉ thị hoá học (chemical indicator) trên gói tiệt khuẩn dùng để:', '["Đánh dấu hạn dùng", "Xác nhận gói đã trải qua chu trình tiệt khuẩn (chuyển màu) - không thay thế biological indicator", "Tăng độ vô khuẩn", "Trang trí"]'::jsonb, 1, 'Indicator chuyển màu = đã vào lò tiệt khuẩn, NHƯNG cần biological indicator định kỳ để xác nhận diệt khuẩn hoàn toàn.', '', ARRAY['KT06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0188', 'S3.6', 1, 'single_choice', 'Dụng cụ thép không gỉ sau tiệt khuẩn có hạn dùng:', '["1 ngày", "Tuỳ loại bao bì + điều kiện bảo quản (thường 30 ngày với bao giấy, lâu hơn với bao plasma)", "1 năm", "Vĩnh viễn"]'::jsonb, 1, 'Hạn dùng phụ thuộc bao bì: giấy crepe khoảng 30 ngày, plasma wrap khoảng 6 tháng+, theo SOP nội bộ.', '', ARRAY['KT06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0189', 'S3.6', 2, 'single_choice', 'Kim, dao mổ, gạc bẩn sau mổ phân loại vào:', '["Thùng đen", "Thùng vàng có biểu tượng nguy hại sinh học", "Thùng cứng kháng thủng + thùng vàng cho gạc/băng", "Thùng xanh"]'::jsonb, 2, 'Sắc nhọn → thùng cứng kháng thủng (thường vàng). Gạc/băng/dụng cụ tiêu hao có máu → thùng vàng lây nhiễm.', '', ARRAY['KT06','VB09'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0190', 'S3.6', 2, 'single_choice', 'Dụng cụ phẫu thuật endoscopic (nội soi) tái sử dụng cần khử/tiệt khuẩn theo mức:', '["Khử khuẩn mức thấp", "Khử khuẩn mức cao (HLD) vì tiếp xúc niêm mạc", "Tiệt khuẩn vì tiếp xúc mô vô khuẩn", "Tuỳ trường hợp"]'::jsonb, 1, 'Dụng cụ tiếp xúc niêm mạc (endoscope mềm) cần HLD. Tiếp xúc mô vô khuẩn (forceps) cần tiệt khuẩn theo Spaulding.', '', ARRAY['KT06','VB09'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0191', 'S3.6', 3, 'single_choice', 'Sau ca mổ NB nhiễm HIV, xử lý dụng cụ tái sử dụng:', '["Vứt tất cả", "Xử lý theo quy trình thông thường - không cần đặc biệt vì vẫn vô khuẩn", "Đeo PPE đầy đủ + ngâm dung dịch khử nhiễm + xử lý theo SOP chuẩn", "Đốt"]'::jsonb, 2, 'Theo phòng ngừa chuẩn, dụng cụ HIV xử lý như thông thường nhưng ĐD phải có PPE đầy đủ. Tiệt khuẩn diệt được HIV.', '', ARRAY['KT06','VB09'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0192', 'S3.6', 1, 'single_choice', 'Trước ca mổ, kiểm tra dụng cụ điện (dao điện, máy hút) phải:', '["Bật thử", "Kiểm tra dây nguồn, đầu kết nối, công suất - test trước rạch da", "Không cần", "Để PTV tự kiểm tra"]'::jsonb, 1, 'ĐD chạy ngoài phải test dụng cụ điện trước ca mổ, đảm bảo hoạt động + an toàn điện.', '', ARRAY['KT06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0193', 'S3.7', 1, 'single_choice', 'Trước đặt sonde Foley, ĐD vệ sinh tay theo cấp độ:', '["Rửa tay thường", "Rửa tay vô khuẩn (surgical hand antisepsis)", "Rửa tay phẫu thuật", "Không cần"]'::jsonb, 1, 'Đặt sonde tiểu là kỹ thuật vô khuẩn cần rửa tay vô khuẩn + găng vô khuẩn.', '', ARRAY['BK02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0194', 'S3.7', 2, 'single_choice', 'Khi đặt sonde Foley cho nam giới, dương vật được giữ ở góc:', '["0 độ (ngang)", "30 độ (chếch nhẹ)", "60-90 độ (gần vuông góc với bụng) để giãn niệu đạo", "180 độ"]'::jsonb, 2, 'Giữ dương vật vuông góc bụng để giãn niệu đạo, dễ luồn sonde. Sau khi sonde đi qua góc cong, hạ xuống.', '', ARRAY['BK02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0195', 'S3.7', 2, 'single_choice', 'Sau khi bơm bóng chèn sonde Foley, ĐD cần:', '["Rút ngay", "Nhẹ nhàng kéo sonde đến khi cảm thấy lực cản (bóng đã vào bàng quang)", "Đẩy thêm vào", "Cố định ngay"]'::jsonb, 1, 'Sau bơm bóng, kéo sonde nhẹ đến khi gặp lực cản - bóng đã vào bàng quang.', '', ARRAY['BK02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0196', 'S3.7', 3, 'single_choice', 'Khi đặt sonde, NB nam kêu đau dữ dội + chảy máu niệu đạo, xử trí?', '["Cố đẩy sonde mạnh hơn", "DỪNG ngay, không rút mà cũng không đẩy, báo BS hội chẩn niệu khoa", "Rút sonde luôn", "Bơm thêm gel"]'::jsonb, 1, 'Đau + chảy máu = nghi tổn thương niệu đạo. KHÔNG đẩy thêm, KHÔNG rút, gọi niệu khoa.', '', ARRAY['BK02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0197', 'S3.7', 1, 'single_choice', 'Sonde Foley 3 nhánh khác 2 nhánh ở:', '["Có thêm đường rửa bàng quang (irrigation channel)", "Kích thước lớn hơn", "Vật liệu", "Màu sắc"]'::jsonb, 0, 'Sonde 3 nhánh có 3 lumen: dẫn nước tiểu, bơm bóng, đường rửa - dùng sau PT tiết niệu.', '', ARRAY['BK02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0198', 'S3.7', 2, 'single_choice', 'Để giảm nhiễm khuẩn niệu liên quan sonde (CAUTI), nguyên tắc nào QUAN TRỌNG nhất?', '["Thay sonde mỗi ngày", "Chỉ đặt khi cần thiết + rút sớm nhất có thể", "Dùng kháng sinh dự phòng", "Tăng cường vệ sinh"]'::jsonb, 1, 'CDC: chỉ đặt khi cần + rút sớm là biện pháp hiệu quả nhất giảm CAUTI.', '', ARRAY['BK02','VB09'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0199', 'S3.7', 2, 'single_choice', 'Túi đựng nước tiểu phải đặt ở vị trí:', '["Cao hơn bàng quang", "Thấp hơn bàng quang (luôn dưới mức cơ thể) - tránh trào ngược", "Cùng mức", "Tuỳ ý"]'::jsonb, 1, 'Túi luôn ở dưới mức bàng quang để nước tiểu chảy theo trọng lực + tránh trào ngược.', '', ARRAY['BK02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0200', 'S3.7', 1, 'single_choice', 'Cố định sonde Foley ở vị trí nào cho NB nam?', '["Vùng đùi trên", "Vùng bụng dưới (giảm góc gập, giảm áp lực niệu đạo)", "Vùng cẳng chân", "Không cần cố định"]'::jsonb, 1, 'Nam giới: cố định bụng dưới. Nữ: cố định đùi trên trong.', '', ARRAY['BK02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0201', 'S3.8', 1, 'single_choice', 'Trong khởi mê đặt NKQ, ĐD GM chuẩn bị:', '["Chỉ thuốc mê", "Đầy đủ: máy GM check, ống NKQ các size, đèn đặt, bóng Ambu, thuốc cấp cứu, monitor", "Chỉ đèn đặt", "Để BS tự chuẩn bị"]'::jsonb, 1, 'Chuẩn bị đầy đủ bộ đặt NKQ + monitor + thuốc cấp cứu là vai trò chính của ĐD GM trong khởi mê.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0202', 'S3.8', 2, 'single_choice', 'Trước khi BS đặt NKQ, ĐD đặt NB ở tư thế:', '["Nằm sấp", "Nằm ngửa, đầu cao sniffing position (gập cổ + ngửa đầu)", "Nằm nghiêng", "Ngồi"]'::jsonb, 1, 'Tư thế sniffing làm thẳng trục miệng-họng-thanh quản, dễ đặt NKQ.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0203', 'S3.8', 2, 'single_choice', 'Khi BS đặt NKQ, ĐD GM thực hiện thủ thuật BURP ở:', '["Bụng", "Sụn nhẫn hoặc sụn giáp - đẩy thanh quản về sau, lên trên, sang phải", "Đầu", "Vai"]'::jsonb, 1, 'BURP/Cricoid pressure: ấn sụn giáp/nhẫn để bộc lộ thanh môn cho BS dễ thấy.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0204', 'S3.8', 1, 'single_choice', 'Sau khi đặt NKQ, xác nhận vị trí ống bằng:', '["Quan sát ngực", "Nghe phổi 2 bên + EtCO2 + SpO2 + hơi nước trong ống", "Chỉ chụp X-quang", "Cảm giác BS"]'::jsonb, 1, 'Xác nhận đa biện pháp: nghe phổi 2 bên đều, EtCO2 dương, SpO2 ổn, X-quang xác nhận sau.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0205', 'S3.8', 2, 'single_choice', 'Áp lực bóng chèn ống NKQ (cuff) ngay sau đặt phải đạt:', '["5-10 cmH2O", "15-20 cmH2O", "20-30 cmH2O", "40-50 cmH2O"]'::jsonb, 2, 'Áp lực cuff 20-30 cmH2O: đủ kín không rò khí, không gây thiếu máu niêm mạc khí quản.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0206', 'S3.8', 3, 'single_choice', 'NB tỉnh khi tiêm propofol, BS yêu cầu thêm liều. Trước khi tiêm thêm, ĐD GM phải:', '["Tiêm ngay", "Đối chiếu lại y lệnh + tên thuốc + liều + đường dùng (5 đúng), thông báo BS", "Hỏi thân nhân", "Không cần làm gì"]'::jsonb, 1, 'Thuốc cấp cứu/gây mê tiêm IV cần 5 đúng + đối chiếu BS dù gấp.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0207', 'S3.8', 2, 'single_choice', 'Trong khi đặt NKQ, NB đột ngột SpO2 tụt dưới 85%. Xử trí ưu tiên?', '["Cố gắng đặt nhanh hơn", "DỪNG đặt - thông khí bóng Ambu + oxy 100% trước khi đặt lại", "Tăng liều thuốc mê", "Báo gia đình"]'::jsonb, 1, 'Quy tắc: SpO2 < 90% kéo dài thì DỪNG đặt, oxygenate. Thử lại sau khi SpO2 trên 95%.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0208', 'S3.8', 1, 'single_choice', 'Thuốc khởi mê IV thường dùng:', '["Propofol, Etomidate, Ketamine, Thiopental", "Adrenalin", "Atropin đơn độc", "Saline"]'::jsonb, 0, '4 thuốc khởi mê chính: Propofol, Etomidate, Ketamine, Thiopental.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0209', 'S3.8', 2, 'single_choice', 'Thuốc giãn cơ trong đặt NKQ có 2 nhóm:', '["Khử cực (succinylcholine) + không khử cực (rocuronium, vecuronium...)", "Chỉ succinylcholine", "Chỉ rocuronium", "Không cần giãn cơ"]'::jsonb, 0, 'Khử cực: succinylcholine nhanh, hết nhanh. Không khử cực: rocuronium, vecuronium dài hơn, an toàn tim mạch.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0210', 'S3.8', 3, 'single_choice', 'NB sau đặt NKQ, monitor báo EtCO2 dao động bất thường, SpO2 tụt dần, áp lực đường thở tăng. Nghi nguyên nhân nào (DOPE)?', '["Dislodgement, Obstruction, Pneumothorax, Equipment failure", "Chỉ tắc ống", "Chỉ rời ống", "Không có vấn đề"]'::jsonb, 0, 'DOPE: Dislodgement (lệch), Obstruction (tắc), Pneumothorax (TKMP), Equipment (máy hỏng) - 4 nguyên nhân chính khi NB thở máy gặp vấn đề.', '*', ARRAY['BK03','CS04'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0211', 'S4.4', 1, 'single_choice', 'Tem dán VTYT bắt buộc phải có thông tin nào?', '["Tên VTYT", "Số lô + hạn dùng", "Đơn vị nhập + ngày tiệt khuẩn (nếu áp dụng)", "Tất cả các đáp án trên"]'::jsonb, 3, 'Tem chuẩn: tên + lô + hạn + đơn vị + ngày tiệt khuẩn nếu là dụng cụ tái sử dụng.', '', ARRAY['KT07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0212', 'S4.4', 1, 'single_choice', 'VTYT hết hạn được xử lý thế nào?', '["Vẫn dùng nếu còn nguyên bao bì", "Loại bỏ theo quy trình KSNK + ghi nhận biên bản huỷ", "Đem sang khoa khác", "Bán lại"]'::jsonb, 1, 'VTYT hết hạn không an toàn cần loại bỏ theo quy trình + biên bản.', '', ARRAY['KT07','VB09'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0213', 'S4.4', 2, 'single_choice', 'Kiểm kê VTYT trong khoa được thực hiện định kỳ:', '["Hàng tháng", "Hàng quý", "Cả 2 - định kỳ + đột xuất khi cần", "Khi có sự cố"]'::jsonb, 2, 'Kiểm kê định kỳ tháng/quý + đột xuất khi bàn giao, sự cố, kết thúc tài khoá.', '', ARRAY['KT07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0214', 'S4.4', 2, 'single_choice', 'Khi nhập VTYT mới, ĐD phụ trách phải kiểm tra:', '["Số lượng theo hoá đơn", "Hạn dùng còn lại", "Bao bì nguyên vẹn + chứng từ kèm theo", "Tất cả các đáp án"]'::jsonb, 3, 'Kiểm tra đầy đủ trước khi ký nhận: số lượng, hạn dùng, bao bì, chứng từ kèm.', '', ARRAY['KT07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0215', 'S4.4', 1, 'single_choice', 'Nguyên tắc FIFO trong quản lý VTYT là gì?', '["First In First Out - vào trước ra trước (dùng VTYT cũ trước)", "Last In First Out", "Theo size", "Tuỳ ý"]'::jsonb, 0, 'FIFO: dùng VTYT nhập trước (sắp hết hạn hơn) trước - giảm lãng phí, đảm bảo chất lượng.', '', ARRAY['KT07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0216', 'S4.4', 2, 'single_choice', 'Thuốc gây nghiện và thuốc tâm thần được quản lý theo quy định nào?', '["TT 20/2017 + TT 12/2018", "TT 32/2023", "TT 31/2021", "Không có quy định riêng"]'::jsonb, 0, 'Thuốc gây nghiện/hướng thần quản lý theo TT 20/2017 + TT 12/2018. Bảo quản riêng, sổ riêng, kiểm 2 người.', '', ARRAY['KT07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0217', 'S4.4', 3, 'single_choice', 'Phát hiện VTYT bị nghi giả/kém chất lượng (tem mờ, bao bì lỗi), xử trí?', '["Vẫn dùng", "Cách ly lô đó + báo cáo Trưởng khoa + Phòng Dược + niêm phong", "Đem trả nhà cung cấp ngay", "Bỏ qua"]'::jsonb, 1, 'Niêm phong cách ly + báo cáo theo cấp - không tự ý xử lý.', '', ARRAY['KT07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0218', 'S4.4', 2, 'single_choice', 'Tủ thuốc cấp cứu cần kiểm tra:', '["Tuần 1 lần", "Sau mỗi lần sử dụng + ít nhất mỗi tuần (theo SOP nội bộ)", "Tháng 1 lần", "Khi cần"]'::jsonb, 1, 'Crash cart phải full + nguyên niêm phong - kiểm tra sau mỗi lần dùng + định kỳ hàng tuần.', '', ARRAY['KT07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0219', 'S5.3', 1, 'single_choice', 'NB sau gây mê NKQ, đột nhiên ngừng thở. Bước đầu tiên?', '["Gọi BS", "Thông khí bóng Ambu + oxy 100%, đặt lại NKQ nếu cần, gọi cấp cứu", "Tiêm thuốc", "Chờ NB tự thở"]'::jsonb, 1, 'Ngừng thở sau GM cần thông khí ngay + gọi hỗ trợ.', '+', ARRAY['CS07','BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0220', 'S5.3', 2, 'single_choice', 'NB hồi tỉnh có Aldrete 5/10, mạch 50, HA 80/45. Xử trí?', '["Chuyển về phòng thường", "Tiếp tục theo dõi + báo BS + đánh giá nguyên nhân tụt HA/nhịp chậm", "Cho ra viện", "Cho ăn"]'::jsonb, 1, 'Aldrete < 9 + sinh hiệu bất ổn = chưa đủ điều kiện rời PACU.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0221', 'S5.3', 3, 'single_choice', 'NB sau rút NKQ, run lạnh dữ dội, nhiệt độ 35.5°C. Cơ chế?', '["Mất nhiệt trong mổ + hồi nhiệt sau mổ + run cơ tạo nhiệt", "Sốt nhiễm khuẩn", "Tác dụng phụ thuốc", "Tâm lý"]'::jsonb, 0, 'Hypothermia trong mổ thường gặp. Run cơ là phản ứng sinh nhiệt - cần ủ ấm chủ động.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0222', 'S5.3', 2, 'single_choice', 'NB nôn sau gây mê, xử trí ngay là:', '["Chỉ chờ qua", "Đặt đầu nghiêng + hút sạch + ondansetron theo y lệnh", "Cho uống nước", "Cho ăn nhẹ"]'::jsonb, 1, 'Phòng hít sặc: nghiêng đầu, hút đường thở, thuốc chống nôn.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0223', 'S5.3', 1, 'single_choice', 'Đau sau mổ được đánh giá bằng thang nào tiêu chuẩn?', '["VAS, NRS, FACES", "Aldrete", "GCS", "Cả 3 đáp án"]'::jsonb, 0, 'VAS 0-10, NRS 0-10, FACES cho trẻ em + người không hợp tác.', '', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0224', 'S5.3', 3, 'single_choice', 'NB tỉnh sau GM, đột ngột tím mặt, SpO2 70%, không thở rít. Nghĩ đến:', '["Phù thanh quản", "Co thắt thanh quản (laryngospasm) - cấp cứu khẩn", "Hen", "Tâm lý"]'::jsonb, 1, 'Laryngospasm: thắt cơ thanh quản đột ngột. Xử trí: oxy + cố gắng thông khí dương, succinylcholine nếu không cải thiện.', '+', ARRAY['CS07','BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0225', 'S5.3', 2, 'single_choice', 'Sau mổ, NB tỉnh có biểu hiện kích động, nhổm dậy. Xử trí?', '["Trói tay", "Tìm nguyên nhân (đau, lo âu, hạ oxy, hạ đường huyết...) + giữ an toàn + báo BS", "Cho thuốc an thần", "Bỏ qua"]'::jsonb, 1, 'Emergence delirium thường do nhiều nguyên nhân - đánh giá rồi xử trí. Giữ an toàn NB.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0226', 'S5.3', 3, 'single_choice', 'NB sau gây mê, tỉnh đột ngột, đau ngực, SpO2 90%, ECG ST chênh. Xử trí?', '["Cho thuốc giảm đau", "Nghĩ nhồi máu cơ tim chu mổ - oxy + ECG 12 đạo + báo BS tim mạch + chuẩn bị cấp cứu", "Cho NB nghỉ", "Cho ăn"]'::jsonb, 1, 'Đau ngực + thay đổi ECG sau mổ = nhồi máu cơ tim chu mổ - cấp cứu nội tim mạch.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0227', 'S5.3', 2, 'single_choice', 'Tiêu chuẩn xuất viện khỏi PACU bao gồm:', '["Aldrete trên 9", "Sinh hiệu ổn", "Đau kiểm soát (VAS dưới 3) + không buồn nôn", "Tất cả các đáp án"]'::jsonb, 3, 'Tiêu chuẩn rời PACU: Aldrete trên 9 + sinh hiệu ổn + đau dưới 3 + không nôn + an toàn để chuyển.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0228', 'S5.3', 2, 'single_choice', 'NB sau mổ ngày 1, sinh hiệu ổn nhưng kêu khó thở khi nằm xuống. Nghĩ đến nguyên nhân?', '["Atelectasis (xẹp phổi do thở nông sau mổ)", "TKMP", "Suy tim cấp", "Cả 3 đều có thể"]'::jsonb, 3, 'Khó thở sau mổ có nhiều nguyên nhân. Cần đánh giá toàn diện.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0229', 'S6.3', 1, 'single_choice', 'Bảng kiểm đánh giá thực hành (checklist) dùng để:', '["Trừng phạt nhân viên sai", "Chuẩn hoá quy trình + đánh giá khách quan + công cụ đào tạo + cải tiến chất lượng", "Thay thế hoàn toàn nhận xét", "Lập kế hoạch nhân sự"]'::jsonb, 1, 'Bảng kiểm là công cụ đánh giá khách quan, đào tạo, cải tiến - KHÔNG phải để trừng phạt.', '', ARRAY['BK01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0230', 'S6.3', 1, 'single_choice', 'Thang điểm chuẩn cho bảng kiểm thực hành thường là:', '["Đúng/Sai", "0-1-2 (chưa làm/làm chưa đúng/làm đúng) cho từng bước", "Tự do", "1-10"]'::jsonb, 1, 'Thang 3 mức 0-1-2 phổ biến: 0 = chưa làm, 1 = chưa đầy đủ, 2 = làm đúng đủ.', '', ARRAY['BK01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0231', 'S6.3', 2, 'single_choice', 'Trong đánh giá thực hành bằng bảng kiểm, ai có thể là người đánh giá?', '["Trưởng khoa", "ĐD trưởng khoa", "BS chuyên khoa", "Tất cả (theo SOP đơn vị)"]'::jsonb, 3, 'Người đánh giá có thể là trưởng khoa, ĐD trưởng, BS - theo phân công và năng lực.', '', ARRAY['BK01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0232', 'S6.3', 2, 'single_choice', 'Sau khi đánh giá thực hành bằng bảng kiểm, người được đánh giá nên:', '["Không biết kết quả", "Nhận phản hồi chi tiết về điểm mạnh/yếu + kế hoạch cải thiện", "Bị trừ lương", "Chuyển khoa"]'::jsonb, 1, 'Phản hồi xây dựng + kế hoạch hành động là mục đích chính.', '', ARRAY['BK01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0233', 'S6.3', 1, 'single_choice', 'Tần suất đánh giá thực hành định kỳ tiêu chuẩn cho ĐD trong khoa:', '["Hàng ngày", "Hàng tháng cho ĐD mới + định kỳ 6 tháng - 1 năm cho ĐD đã ổn định", "Hàng tuần", "Hàng năm cho mọi cấp"]'::jsonb, 1, 'ĐD mới đánh giá thường xuyên, ĐD ổn định 6 tháng - 1 năm theo SOP.', '', ARRAY['BK01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0234', 'S6.3', 2, 'single_choice', 'Trong bảng kiểm, mục ''tiêu chuẩn không thể bỏ sót'' (critical items) là:', '["Mọi bước đều quan trọng như nhau", "Các bước về an toàn người bệnh (vô khuẩn, định danh, đối soát thuốc...) - sai 1 mục critical = không đạt", "Bước nhanh nhất", "Bước cuối"]'::jsonb, 1, 'Critical items liên quan an toàn NB. Sai 1 critical = không đạt dù điểm tổng cao.', '', ARRAY['BK01','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0235', 'S6.3', 3, 'single_choice', 'NB tử vong trong ca mổ. ĐD GM bị đánh giá tỷ lệ dưới 70% trong bảng kiểm. Xử trí?', '["Đuổi việc", "Đánh giá lại theo SOP - phân tích lỗi hệ thống vs lỗi cá nhân, đào tạo bổ sung, hội đồng chuyên môn", "Khiển trách công khai", "Bỏ qua"]'::jsonb, 1, 'Phân tích root cause: hệ thống thường có vai trò lớn hơn cá nhân. Đào tạo + cải tiến quy trình.', '', ARRAY['BK01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0236', 'S6.3', 1, 'single_choice', 'Bảng kiểm an toàn phẫu thuật WHO có bao nhiêu giai đoạn?', '["1", "2", "3 (Sign-In, Time-Out, Sign-Out)", "5"]'::jsonb, 2, 'WHO Surgical Safety Checklist 3 giai đoạn: Sign-In + Time-Out + Sign-Out.', '', ARRAY['BK01','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
-- ============================================
-- PART 3: Balance skill counts + more Lv 3 clinical scenarios
-- Q0237-Q0306 (70 questions)
-- ============================================

-- S1.1 Đạo đức nghề nghiệp (+3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0237', 'S1.1', 2, 'single_choice', 'NB cao tuổi không có thân nhân, NB từ chối ký cam kết phẫu thuật. ĐD nên:', '["Ép NB ký", "Tôn trọng quyền tự quyết + thông báo BS + ghi nhận hồ sơ + hội chẩn nếu cần", "Ký thay NB", "Bỏ qua"]'::jsonb, 1, 'Tôn trọng quyền tự quyết của NB là nguyên tắc đạo đức cốt lõi - không được ép buộc hay ký thay.', '', ARRAY['VB02','VB11'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0238', 'S1.1', 3, 'single_choice', 'ĐD phát hiện đồng nghiệp dùng nhầm thuốc cho NB nhưng đồng nghiệp xin giấu vì sợ kỷ luật. Đúng đạo đức là:', '["Giấu giúp đồng nghiệp", "Báo cáo sự cố theo SOP + ưu tiên an toàn NB - không che giấu", "Bỏ qua nếu NB không sao", "Nói với gia đình NB"]'::jsonb, 1, 'An toàn NB trên hết - báo cáo sự cố là nghĩa vụ đạo đức + pháp lý.', '', ARRAY['VB02','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0239', 'S1.1', 2, 'single_choice', 'Gia đình NB tặng phong bì cảm ơn sau ca mổ thành công. ĐD nên:', '["Nhận để không làm họ tự ái", "Cảm ơn nhưng từ chối + giải thích quy định bệnh viện", "Nhận rồi nộp lại", "Báo cáo NB"]'::jsonb, 1, 'Liêm chính nghề nghiệp - từ chối lịch sự là chuẩn mực đạo đức.', '', ARRAY['VB02'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S2.1 Giao tiếp với NB (+3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0240', 'S2.1', 1, 'single_choice', 'Khi giới thiệu bản thân với NB lần đầu, ĐD cần:', '["Chỉ nói tên", "Tên + chức danh + vai trò trong ca chăm sóc + thẻ tên rõ ràng", "Tên + khoa", "Chỉ thẻ tên"]'::jsonb, 1, 'Giới thiệu đầy đủ giúp NB an tâm và biết ai chăm sóc mình.', '', ARRAY['CS06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0241', 'S2.1', 2, 'single_choice', 'NB tỉnh ngộ sau mê hỏi: ''Tôi có sao không?''. Trả lời phù hợp nhất:', '["''Không sao đâu''", "''Cô/chú vừa mổ xong, mọi việc ổn, tôi sẽ giải thích chi tiết khi BS đến nhé''", "''Tôi không biết''", "''Hỏi BS''"]'::jsonb, 1, 'Trấn an + cung cấp thông tin trong phạm vi chuyên môn + chuyển BS giải thích chi tiết.', '', ARRAY['CS06','CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0242', 'S2.1', 3, 'single_choice', 'NB lo lắng tột độ trước mổ, run, khóc. Kỹ thuật giao tiếp hiệu quả:', '["Bỏ NB tự ổn định", "Active listening + đồng cảm + cung cấp thông tin rõ ràng + hỗ trợ tinh thần + báo BS gây mê", "Cho thuốc an thần ngay", "Hoãn mổ"]'::jsonb, 1, 'Tâm lý trước mổ ảnh hưởng kết quả - chăm sóc tâm lý là phần quan trọng.', '', ARRAY['CS06'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S2.2 Giao tiếp với đồng nghiệp (+3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0243', 'S2.2', 2, 'single_choice', 'Bàn giao ca mổ cho ekip kế tiếp, công cụ chuẩn nên dùng:', '["Tự do nói", "SBAR (Situation - Background - Assessment - Recommendation)", "Chỉ viết", "Bỏ qua"]'::jsonb, 1, 'SBAR là công cụ giao tiếp chuẩn quốc tế - giảm sai sót khi handoff.', '', ARRAY['CS06','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0244', 'S2.2', 2, 'single_choice', 'Khi nhận y lệnh miệng (verbal order), ĐD bắt buộc phải:', '["Thực hiện ngay", "Repeat-back: nhắc lại y lệnh + xác nhận lại với BS + ghi nhận trong 24h", "Ghi vào sổ", "Hỏi y tá khác"]'::jsonb, 1, 'Read-back/Repeat-back là tiêu chuẩn an toàn quốc tế - giảm sai y lệnh.', '', ARRAY['CS06','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0245', 'S2.2', 3, 'single_choice', 'BS y lệnh dùng thuốc liều cao bất thường, NB già có suy thận. ĐD nên:', '["Thực hiện không thắc mắc", "Trao đổi lịch sự với BS - nêu lý do nghi ngờ - confirm liều - ghi nhận hồ sơ", "Báo trưởng khoa", "Bỏ qua"]'::jsonb, 1, 'ĐD là rào chắn cuối cùng (last barrier) - quyền và trách nhiệm thắc mắc y lệnh nghi ngờ.', '', ARRAY['CS06','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S2.3 Bảo mật thông tin (+3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0246', 'S2.3', 1, 'single_choice', 'NĐ 13/2023 quy định bảo vệ dữ liệu cá nhân (PDPL) - ngoài tên tuổi địa chỉ, dữ liệu nào được coi là "nhạy cảm"?', '["Sở thích cá nhân", "Tình trạng sức khỏe + dữ liệu y tế + sinh trắc học + định danh sinh học", "Sở thích du lịch", "Sở thích thực phẩm"]'::jsonb, 1, 'NĐ 13/2023 liệt kê dữ liệu nhạy cảm gồm sức khoẻ, y tế - cần bảo mật chặt chẽ.', '', ARRAY['VB12'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0247', 'S2.3', 2, 'single_choice', 'Phóng viên xin chụp ảnh NB sau ca mổ ''anh hùng''. Đúng quy định là:', '["Cho phép vì lý do PR", "Cần đồng ý bằng văn bản của NB/thân nhân + che danh tính nếu cần + báo bệnh viện", "Hỏi BS", "Chụp luôn"]'::jsonb, 1, 'Quyền hình ảnh + dữ liệu y tế cần đồng ý có hiệu lực + tuân thủ NĐ 13/2023 + quy định BV.', '', ARRAY['VB12'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0248', 'S2.3', 3, 'single_choice', 'ĐD chụp ảnh ca mổ đặc biệt rồi đăng Facebook (có che mặt NB). Đánh giá:', '["Hợp lệ vì đã che mặt", "VI PHẠM dù che mặt - vẫn có thể nhận diện qua bối cảnh + chưa có đồng ý + vi phạm bí mật nghề nghiệp", "Không sao nếu không tag NB", "Hợp lệ nếu không bình luận tiêu cực"]'::jsonb, 1, 'Bí mật nghề nghiệp + quyền NB - cấm chia sẻ thông tin/hình ảnh NB lên mạng xã hội dù che mặt.', '', ARRAY['VB02','VB12'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S2.5 Đào tạo NB và gia đình (+4)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0249', 'S2.5', 1, 'single_choice', 'Hướng dẫn NB tự chăm sóc sau mổ nội soi, kỹ thuật teach-back có nghĩa:', '["ĐD đọc to", "Yêu cầu NB nhắc lại bằng ngôn ngữ của họ để xác nhận đã hiểu", "Phát tờ rơi", "Cho video"]'::jsonb, 1, 'Teach-back: NB nhắc lại = xác nhận hiểu - giảm tái nhập viện do hướng dẫn sai.', '', ARRAY['CS06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0250', 'S2.5', 2, 'single_choice', 'NB xuất viện sau mổ ổ bụng cần hướng dẫn gồm:', '["Chỉ thuốc", "Thuốc + chăm sóc vết mổ + dinh dưỡng + dấu hiệu cần tái khám + lịch tái khám + số điện thoại liên hệ", "Chỉ tái khám", "Chỉ vết mổ"]'::jsonb, 1, 'Hướng dẫn xuất viện đầy đủ 6 yếu tố - tiêu chuẩn JCI/Bộ Y tế.', '', ARRAY['CS06','CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0251', 'S2.5', 2, 'single_choice', 'NB tiểu đường, mới đặt PCA morphin sau mổ, cần dặn dò gì?', '["Cách bấm PCA + không cho người khác bấm + giới hạn liều/phút (lockout) + dấu hiệu quá liều (buồn ngủ, thở chậm)", "Chỉ cách bấm", "Bấm nhiều cho hết đau", "Không cần dặn"]'::jsonb, 0, 'PCA: chỉ NB bấm + có lockout an toàn + dấu hiệu quá liều opioid cần báo ngay.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0252', 'S2.5', 3, 'single_choice', 'Gia đình NB không biết chữ, cần hướng dẫn uống thuốc nhiều loại sau xuất viện. Cách phù hợp:', '["Phát đơn rồi cho về", "Vẽ sơ đồ thuốc trực quan + dùng hộp chia thuốc theo bữa + dặn đến nhà thuốc bệnh viện sắp xếp + người nhà tin cậy kiểm tra", "Đọc to đơn", "Gọi điện hướng dẫn"]'::jsonb, 1, 'Hướng dẫn cá nhân hoá theo điều kiện NB - mục tiêu là an toàn thuốc tại nhà.', '', ARRAY['CS06'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S2.6 Làm việc nhóm (+4)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0253', 'S2.6', 1, 'single_choice', 'Time-out trước mổ là gì?', '["Nghỉ giải lao", "Dừng lại 1-2 phút trước rạch da để toàn team xác nhận: đúng NB + đúng vị trí mổ + đúng thủ thuật + dụng cụ đủ", "Họp giao ban", "Bàn giao ca"]'::jsonb, 1, 'Time-out theo WHO Surgical Safety Checklist - giảm sai vị trí mổ và lỗi nghiêm trọng.', '', ARRAY['BK01','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0254', 'S2.6', 2, 'single_choice', 'Trong ekip mổ, ĐD GM nghi BS phẫu thuật chuẩn bị mổ nhầm bên. ĐD nên:', '["Im lặng vì BS có thẩm quyền", "STOP - lên tiếng ngay - dừng cuộc mổ - đối chiếu hồ sơ - làm rõ trước khi tiếp tục", "Báo sau", "Hỏi đồng nghiệp"]'::jsonb, 1, 'Speak up culture - mọi thành viên team có trách nhiệm + quyền dừng cuộc mổ khi nghi ngờ.', '', ARRAY['BK01','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0255', 'S2.6', 2, 'single_choice', 'CRM (Crisis Resource Management) trong cấp cứu nhấn mạnh:', '["1 người duy nhất xử lý", "Vai trò rõ + giao tiếp closed-loop + chia sẻ tình huống + huy động nguồn lực + lãnh đạo nhóm", "Im lặng tập trung", "Tự ý hành động"]'::jsonb, 1, 'CRM là kỹ năng làm việc nhóm trong khủng hoảng - gốc từ ngành hàng không.', '+', ARRAY['CS06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0256', 'S2.6', 3, 'single_choice', 'NB ngừng tim trên bàn mổ. Ekip cần phân vai:', '["Ai gần nhất làm gì cũng được", "Leader rõ + người ép tim (thay nhau mỗi 2 phút) + người bóp Ambu + người ghi nhận thời gian/thuốc + người chuẩn bị thuốc/máy sốc", "Để leader làm hết", "Không cần phân vai"]'::jsonb, 1, 'Phân vai rõ + xoay vòng tránh mệt + closed-loop communication = CPR hiệu quả.', '+', ARRAY['CS06','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S3.3 Truyền máu (+2 Lv 3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0257', 'S3.3', 3, 'single_choice', 'NB truyền máu lần 2, đột nhiên rét run + sốt 39 + đau lưng + nước tiểu sậm màu. Nghĩ đến:', '["Phản ứng truyền máu cấp tan huyết (acute haemolytic transfusion reaction - AHTR)", "Sốt thông thường", "Sốc tâm lý", "Bệnh tự miễn"]'::jsonb, 0, 'AHTR do nhóm máu không phù hợp - cấp cứu khẩn: dừng truyền, giữ ven, dịch, lasix, kiểm túi máu, báo BS + ngân hàng máu.', '+', ARRAY['KT02','CS03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0258', 'S3.3', 3, 'single_choice', 'NB truyền nhiều khối hồng cầu (>4 đơn vị/24h), nguy cơ cao nào cần dự phòng?', '["Hạ canxi máu (do citrate trong máu lưu trữ chelate Ca) + tăng kali + hạ thân nhiệt + rối loạn đông máu", "Tăng đường", "Suy thận", "Hen"]'::jsonb, 0, 'Massive transfusion: hạ Ca, tăng K, hạ thân nhiệt, coagulopathy - cần theo dõi sát + bù điện giải + sưởi ấm máu truyền.', '+', ARRAY['KT02','CS03'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S3.4 Hồi sức sốc (+3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0259', 'S3.4', 2, 'single_choice', 'NB sốc nhiễm khuẩn, dấu hiệu nào cảnh báo nặng?', '["HA tâm thu dưới 90 dù bù dịch + lactate trên 4 + cần thuốc vận mạch", "Sốt cao", "Đau bụng", "Buồn nôn"]'::jsonb, 0, 'Septic shock = nhiễm khuẩn + tụt HA không đáp ứng dịch + lactate cao + cần vận mạch.', '+', ARRAY['CS01','BK02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0260', 'S3.4', 2, 'single_choice', 'Liều noradrenalin khởi đầu trong sốc nhiễm khuẩn ở người lớn:', '["0.01-0.05 mcg/kg/phút", "5-10 mcg/kg/phút", "100 mcg/phút", "Tuỳ ý"]'::jsonb, 0, 'NA 0.05 - 0.5 mcg/kg/phút - chỉnh theo MAP đích trên 65 mmHg.', '+', ARRAY['CS01','KT05'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0261', 'S3.4', 3, 'single_choice', 'NB shock tim sau nhồi máu cơ tim, HA 80/50, mạch 130, da lạnh ẩm. Liệu pháp KHÔNG phù hợp?', '["Truyền dịch nhanh số lượng lớn (có thể làm phù phổi nặng hơn)", "Vận mạch + thuốc tăng co bóp", "Oxy", "Theo dõi sát"]'::jsonb, 0, 'Shock tim: tim đã suy, truyền dịch nhanh số lượng lớn = nguy cơ phù phổi. Ưu tiên inotropes + vận mạch.', '+', ARRAY['CS01'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S4.1 Phòng ngừa chuẩn (+3, focus Lv 3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0262', 'S4.1', 2, 'single_choice', 'NB nghi nhiễm SARS-CoV-2 trong phòng mổ. Phòng hộ cá nhân (PPE) mức nào?', '["Khẩu trang y tế thông thường", "Khẩu trang N95 + kính chắn giọt bắn + áo choàng chống nước + găng tay + bao giày + mũ", "Chỉ găng tay", "Áo phẫu thuật"]'::jsonb, 1, 'Airborne + droplet + contact precautions - PPE đầy đủ chuẩn N95.', '', ARRAY['CS02','VB07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0263', 'S4.1', 3, 'single_choice', 'ĐD bị kim đâm sau lấy máu NB HIV(+). Xử trí ngay?', '["Bóp nặn máu mạnh", "Rửa nhẹ nhàng vết thương + xà phòng + nước trong 5-10 phút, KHÔNG bóp nặn mạnh - báo cáo - test HIV/HBV/HCV - PEP trong 2h nếu chỉ định", "Sát khuẩn rồi quên đi", "Băng kín"]'::jsonb, 1, 'Phơi nhiễm nghề nghiệp HIV: PEP (Post-exposure prophylaxis) hiệu quả nhất trong 2h. KHÔNG bóp nặn mạnh.', '', ARRAY['CS02','VB07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0264', 'S4.1', 2, 'single_choice', 'Thứ tự đeo PPE chuẩn cho khu vực cách ly:', '["Găng - khẩu trang - mũ - áo", "Vệ sinh tay - áo choàng - khẩu trang/N95 - kính/face shield - găng tay", "Tuỳ ý", "Khẩu trang trước găng"]'::jsonb, 1, 'Thứ tự đeo PPE theo CDC: tay sạch + áo + khẩu trang + kính + găng.', '', ARRAY['CS02','VB07'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S4.2 KSNK (+2)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0265', 'S4.2', 2, 'single_choice', 'Khử khuẩn dụng cụ phẫu thuật theo phân loại Spaulding:', '["Critical - tiệt khuẩn (sterilization). Semi-critical - khử khuẩn mức độ cao. Non-critical - khử khuẩn thấp/sạch", "Tuỳ ý chọn", "Tất cả tiệt khuẩn", "Không phân loại"]'::jsonb, 0, 'Spaulding: critical (xuyên mô) - sterilize; semi-critical (niêm mạc) - HLD; non-critical (da nguyên vẹn) - LLD/clean.', '', ARRAY['CS02','VB07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0266', 'S4.2', 3, 'single_choice', 'Trường hợp ổ dịch viêm phổi liên quan máy thở (VAP) tăng trong khoa GMHS, biện pháp can thiệp dựa trên bằng chứng (VAP bundle):', '["Chỉ rửa tay", "Đầu giường nâng cao 30-45 độ + đánh giá cai máy hàng ngày + DVT prophylaxis + chăm sóc răng miệng chlorhexidine + cai an thần (sedation vacation)", "Đổi kháng sinh", "Cách ly NB"]'::jsonb, 1, 'VAP bundle 5 yếu tố - thực hiện đồng thời giảm tỷ lệ VAP rõ rệt.', '*', ARRAY['CS02','VB07','CS05'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S4.3 Quản lý dụng cụ (+1)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0267', 'S4.3', 3, 'single_choice', 'Tủ tiệt khuẩn hấp đến cuối ngày báo lỗi: chỉ thị sinh học (biological indicator) DƯƠNG tính. Xử trí?', '["Vẫn dùng dụng cụ trong tủ", "Cách ly toàn bộ mẻ tủ + báo KSNK + truy ngược các ca đã dùng dụng cụ từ mẻ trước (nếu nguy cơ) + sửa tủ + tiệt khuẩn lại", "Chỉ kiểm tra mẻ kế tiếp", "Bỏ qua nếu các chỉ thị khác âm"]'::jsonb, 1, 'BI dương = tiệt khuẩn không đạt - phải cách ly mẻ + truy ngược + sửa thiết bị - vấn đề an toàn NB.', '', ARRAY['CS02','VB07'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S5.1 Sơ cứu cấp cứu (+3 Lv 3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0268', 'S5.1', 3, 'single_choice', 'NB trong PACU đột ngột bất tỉnh, không thở, không mạch cảnh. Hành động đầu tiên trong 10s:', '["Tiêm adrenalin", "Gọi cấp cứu + bắt đầu ép tim ngoài lồng ngực ngay (CABD - Chest compression first) + gọi crash cart", "Đặt NKQ", "Truyền dịch"]'::jsonb, 1, 'C-A-B-D (AHA): Compression first - ép tim ngay trong 10 giây phát hiện - tỉ lệ sống tăng đáng kể.', '+', ARRAY['BK04','CS01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0269', 'S5.1', 3, 'single_choice', 'CPR người lớn: tỷ lệ ép tim/thông khí đúng:', '["15:2", "30:2 (nếu chưa đặt NKQ) - liên tục 100-120 lần/phút khi đã đặt NKQ", "5:1", "10:1"]'::jsonb, 1, 'AHA 2020: 30:2 khi chưa NKQ. Sau NKQ ép liên tục + 10 lần thở/phút.', '+', ARRAY['BK04','CS01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0270', 'S5.1', 3, 'single_choice', 'AED phân tích nhịp: rung thất (VF). Xử trí?', '["Tiếp tục ép tim không sốc", "Sốc điện 1 lần ngay + tiếp tục CPR 2 phút - phân tích lại - sốc nếu còn shockable + adrenalin 1mg mỗi 3-5 phút", "Sốc liên tục 3 lần", "Đặt NKQ trước rồi mới sốc"]'::jsonb, 1, 'VF/pVT: sốc đơn lẻ + CPR 2 phút + thuốc - không sốc liên tục, không đặt NKQ trước.', '+', ARRAY['BK04','CS01'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S5.2 Theo dõi NB hậu phẫu (+3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0271', 'S5.2', 2, 'single_choice', 'NB sau mổ ổ bụng, đánh giá dịch dạ dày qua sonde nasogastric. Bất thường cần báo BS?', '["Dịch xanh nhạt", "Máu tươi >50ml/h hoặc dịch màu cà phê + đau bụng + sốc", "Dịch ít", "Dịch trong"]'::jsonb, 1, 'Chảy máu sau mổ ổ bụng là biến chứng nguy hiểm - cần báo ngay.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0272', 'S5.2', 2, 'single_choice', 'Phân loại NEWS2 (National Early Warning Score 2) dùng để:', '["Đánh giá đau", "Cảnh báo sớm tình trạng xấu đi qua các sinh hiệu (RR, SpO2, HA, mạch, ý thức, nhiệt độ)", "Đánh giá vận động", "Đánh giá tâm lý"]'::jsonb, 1, 'NEWS2 là công cụ phát hiện sớm NB nặng - điểm cao yêu cầu can thiệp.', '+', ARRAY['CS07','BK02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0273', 'S5.2', 3, 'single_choice', 'NB sau mổ thay khớp gối ngày 3, đột ngột khó thở + đau ngực kiểu màng phổi + nhịp tim nhanh + SpO2 88%. Nghĩ đến chẩn đoán?', '["Hen", "Thuyên tắc phổi (PE) - hậu phẫu chỉnh hình thay khớp lớn là yếu tố nguy cơ cao", "Lo âu", "Trào ngược"]'::jsonb, 1, 'PE sau mổ thay khớp gối/háng là biến chứng tử vong cao - dấu hiệu khó thở + đau ngực + giảm SpO2 đột ngột.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S6.1 Kế hoạch chăm sóc (+3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0274', 'S6.1', 1, 'single_choice', 'Cấu trúc kế hoạch chăm sóc điều dưỡng theo quy trình ADPIE gồm:', '["Assessment - Diagnosis - Planning - Implementation - Evaluation", "Chỉ thực hiện y lệnh", "Đánh giá - kết thúc", "Không cần kế hoạch"]'::jsonb, 0, 'ADPIE là quy trình điều dưỡng chuẩn quốc tế: Đánh giá + Chẩn đoán + Lập kế hoạch + Thực hiện + Đánh giá.', '', ARRAY['CS06','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0275', 'S6.1', 2, 'single_choice', 'Mục tiêu trong kế hoạch chăm sóc phải đáp ứng tiêu chí SMART nghĩa là:', '["Specific - Measurable - Achievable - Relevant - Time-bound", "Sympathy - Motivation - Active - Real - Tested", "Tự do", "Không cần đo lường"]'::jsonb, 0, 'SMART: cụ thể + đo lường được + khả thi + phù hợp + có thời hạn - tiêu chuẩn viết mục tiêu.', '', ARRAY['CS06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0276', 'S6.1', 3, 'single_choice', 'NB sau mổ thay khớp háng, lập kế hoạch chăm sóc 24h đầu. Ưu tiên hàng đầu trong các chẩn đoán điều dưỡng?', '["Thiếu kiến thức", "Nguy cơ chảy máu / nguy cơ thuyên tắc tĩnh mạch sâu (DVT) / nguy cơ nhiễm khuẩn vết mổ - ABCs trước, biến chứng sống còn ưu tiên", "Khó ngủ", "Buồn chán"]'::jsonb, 1, 'Ưu tiên Maslow + ABCs - biến chứng đe doạ tính mạng trước.', '', ARRAY['CS06','CS07'], 'approved') ON CONFLICT (id) DO NOTHING;

-- S6.2 Ghi nhận hồ sơ (+3)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0277', 'S6.2', 1, 'single_choice', 'Ghi chép hồ sơ điều dưỡng phải đảm bảo:', '["Khách quan + chính xác + đầy đủ + kịp thời (real-time) + có thể đọc + chữ ký rõ + không sửa xoá tuỳ ý", "Chỉ kết quả", "Tóm tắt cuối ca", "Không cần ký"]'::jsonb, 0, 'Nguyên tắc ghi hồ sơ: khách quan + chính xác + đầy đủ + kịp thời + đọc được + ký xác nhận - giá trị pháp lý.', '', ARRAY['VB10','VB02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0278', 'S6.2', 2, 'single_choice', 'Phát hiện sai sót đã ghi trong hồ sơ giấy, cách sửa đúng:', '["Xé bỏ trang đó", "Gạch 1 đường ngang trên thông tin sai (vẫn đọc được nội dung cũ) + ghi đúng kế bên + ký + ghi ngày giờ sửa", "Bút xoá", "Viết đè lên"]'::jsonb, 1, 'KHÔNG xé, không bút xoá, không viết đè - giữ tính minh bạch + pháp lý.', '', ARRAY['VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0279', 'S6.2', 3, 'single_choice', 'NB mất sau ca mổ, hồ sơ có bằng chứng pháp lý quan trọng. Quy định lưu trữ hồ sơ y tế ở VN tối thiểu:', '["1 năm", "Theo TT 33/2008 + quy chế bệnh viện: tối thiểu 10 năm với hồ sơ thông thường, lâu hơn với hồ sơ liên quan tử vong/pháp y", "5 năm", "20 năm cho mọi loại"]'::jsonb, 1, 'Thời gian lưu trữ theo quy chế + loại hồ sơ - hồ sơ liên quan vụ việc pháp lý/tử vong lưu lâu hơn.', '', ARRAY['VB10'], 'approved') ON CONFLICT (id) DO NOTHING;

-- Mixed Lv 3 challenging clinical scenarios (15 questions)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0280', 'S3.1', 3, 'single_choice', 'NB sau gây tê tủy sống đột ngột HA 60/40, mạch 35, nôn. Cơ chế chính + xử trí?', '["Sốc dị ứng - adrenalin", "Block giao cảm cao (high spinal) → giãn mạch + nhịp chậm → dịch + ephedrine/phenylephrine + atropin + Trendelenburg + oxy", "Sốc tâm lý", "Phản xạ vagal đơn thuần"]'::jsonb, 1, 'High spinal cấp cứu: nâng chân + dịch + thuốc co mạch + atropin nếu nhịp chậm.', '*', ARRAY['BK03','CS01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0281', 'S3.5', 3, 'single_choice', 'NB sau khởi mê 5 phút, EtCO2 tăng nhanh đến 80 mmHg, nhịp nhanh, cứng cơ, sốt 39.5°C. Chẩn đoán + xử trí khẩn?', '["Sốt thông thường", "Sốt cao ác tính (Malignant Hyperthermia) - DỪNG halogen, đổi van CO2, dantrolen 2.5 mg/kg, làm lạnh, hỗ trợ tăng thông khí 100% O2, gọi MH hotline", "Hen suyễn", "Nhiễm khuẩn"]'::jsonb, 1, 'MH cấp cứu y khoa - dantrolen là thuốc đặc trị - tử vong cao nếu không xử trí nhanh.', '*', ARRAY['BK03','CS01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0282', 'S3.6', 3, 'single_choice', 'NB sau gây mê NKQ, khó thông khí + áp lực đường thở tăng cao + nghe phổi: ran rít 2 phế trường. Nghi ngờ:', '["Co thắt phế quản (bronchospasm) - tăng FiO2 + sâu hơn mê + salbutamol + ngưng kích thích, loại trừ tắc/lệch ống", "Sốt", "Hạ huyết áp", "Đau"]'::jsonb, 0, 'Bronchospasm là biến chứng GM - xử trí ngay tránh PaO2 tụt.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0283', 'S3.7', 3, 'single_choice', 'NB phản vệ độ III do thuốc gây mê (rocuronium), đang trên bàn mổ. Liều adrenalin IV?', '["1 mg IV", "10-100 mcg IV bolus, lặp lại theo HA, truyền liên tục 0.05-0.5 mcg/kg/min nếu kéo dài", "0.1 mcg", "500 mcg IM"]'::jsonb, 1, 'Adrenalin IV trong shock phản vệ trong gây mê - liều thấp hơn IM, chỉnh theo HA.', '+', ARRAY['CS01','BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0284', 'S3.8', 3, 'single_choice', 'NB béo phì BMI 42, dự kiến đặt NKQ. Chiến lược thông khí trước đặt (preoxygenation) tối ưu:', '["1 phút thở oxy 100%", "3 phút thở oxy 100% qua mặt nạ kín + tư thế ramp/head-up 25 độ + nếu có thể: thông khí áp lực dương không xâm lấn (NIV/CPAP)", "Không cần", "Chỉ thở thường"]'::jsonb, 1, 'NB béo phì có FRC thấp - desaturate nhanh. Preoxygenation kéo dài + tư thế ramp + NIV cải thiện an toàn.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0285', 'S3.2', 3, 'single_choice', 'NB chấn thương đa phát, ĐD GM nhận chăm sóc trong phòng mổ cấp cứu. Ưu tiên cao nhất theo ABCDE?', '["A - Airway with cervical spine protection (kiểm soát đường thở + bảo vệ cột sống cổ)", "B trước A", "Truyền dịch trước", "Báo BS trước"]'::jsonb, 0, 'ATLS: A - Airway with C-spine protection là ưu tiên số 1.', '+', ARRAY['BK02','CS01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0286', 'S1.2', 3, 'single_choice', 'NB không có CMND/giấy tờ trong cấp cứu khẩn cấp, không tỉnh, không thân nhân. Quy định pháp lý cho phép:', '["Không được mổ vì thiếu giấy tờ", "Cấp cứu khẩn cứu sống được phép thực hiện trước - BS trưởng ca quyết định, có biên bản hội chẩn, ghi hồ sơ rõ - sau đó hoàn thiện giấy tờ", "Báo công an trước rồi mới mổ", "Chờ thân nhân"]'::jsonb, 1, 'Quy định cấp cứu khẩn cấp + nguyên tắc cứu người - được thực hiện trước, giấy tờ hoàn thiện sau.', '+', ARRAY['VB02','VB11'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0287', 'S1.3', 3, 'single_choice', 'NB là trẻ vị thành niên 16 tuổi, cần truyền máu cấp cứu (chấn thương). Bố mẹ vì lý do tôn giáo từ chối. Đúng pháp lý là:', '["Tôn trọng quyết định gia đình", "Cấp cứu cứu sống > quyền tự quyết của thân nhân về trẻ vị thành niên - báo cáo lãnh đạo + hội chẩn + thực hiện truyền - ghi nhận đầy đủ + có thể xin lệnh toà án nếu có thời gian", "Chuyển viện khác", "Chỉ truyền dịch"]'::jsonb, 1, 'Quyền sống của trẻ > quyền quyết định tôn giáo của cha mẹ trong cấp cứu - quy tắc đạo đức và pháp lý phổ biến.', '+', ARRAY['VB02','VB11'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0288', 'S3.5', 3, 'single_choice', 'NB sau mổ tỉnh chậm bất thường (>2h sau ngưng thuốc mê), GCS 8, không tự thở đủ. Nguyên nhân cần loại trừ?', '["Lượng thuốc mê còn tồn (residual) + giảm chuyển hoá (suy gan/thận) + tăng cảm thụ + hạ thân nhiệt + rối loạn chuyển hoá (đường, điện giải)", "Chỉ mệt", "Tâm lý", "Lười tỉnh"]'::jsonb, 0, 'Tỉnh chậm sau mê có nhiều nguyên nhân - đánh giá toàn diện + hỗ trợ hô hấp + tìm nguyên nhân.', '+', ARRAY['BK03','CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0289', 'S3.6', 3, 'single_choice', 'Trong khi mổ nội soi ổ bụng, NB tụt SpO2 + EtCO2 tụt + áp lực đường thở tăng + tụt HA. Nghi ngờ:', '["Tắc CO2 embolism (thuyên tắc CO2)", "Sốt", "Đau", "Chảy máu"]'::jsonb, 0, 'CO2 embolism là biến chứng nguy hiểm trong nội soi ổ bụng - dừng bơm CO2 + nghiêng trái + oxy 100% + báo PT.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0290', 'S3.7', 3, 'single_choice', 'NB tiền sử dị ứng penicillin được kê cephalosporin thế hệ 3 (ceftriaxone). Quản lý nguy cơ:', '["Cho thuốc luôn vì cephalosporin khác hẳn", "Đánh giá cross-reactivity (thấp với gen3 nhưng vẫn có) + theo dõi sát 30 phút đầu + có sẵn xe cấp cứu phản vệ + giải thích NB + ghi nhận đồng ý", "Đổi sang quinolone", "Không cần lưu ý"]'::jsonb, 1, 'Cross-reactivity penicillin-cephalosporin gen3 rất thấp nhưng có. Theo dõi + chuẩn bị cấp cứu là tiêu chuẩn.', '+', ARRAY['CS01'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0291', 'S4.4', 3, 'single_choice', 'Phát hiện thuốc giả/lậu (không có nguồn gốc) trong kho khoa. Hành động:', '["Bỏ luôn", "Niêm phong - báo Trưởng khoa + Phòng Dược + Phòng Quản lý chất lượng + có thể báo cơ quan chức năng - lập biên bản - không tiêu huỷ tự ý", "Đem trả nhà cung cấp", "Bán giảm giá"]'::jsonb, 1, 'Thuốc giả là vấn đề pháp lý + chất lượng - cần báo cáo cấp + niêm phong làm bằng chứng.', '', ARRAY['KT07','VB02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0292', 'S5.1', 3, 'single_choice', 'NB ngưng tim trong phòng mổ, sau 10 phút CPR vẫn không có ROSC, ECG: asystole. Tiếp tục hay dừng?', '["Dừng ngay", "Tiếp tục CPR + xem xét nguyên nhân có thể hồi phục (5H5T) + adrenalin 1mg/3-5 phút + chỉ ngừng khi có đồng thuận team + đạt tiêu chí dừng (kéo dài + không nguyên nhân hồi phục + ý kiến gia đình nếu áp dụng)", "Sốc điện asystole", "Cho thuốc atropin"]'::jsonb, 1, 'Asystole KHÔNG shockable. Tiếp tục CPR + tìm 5H5T (Hypoxia, Hypovolemia, H+, Hypo/HyperK, Hypothermia + Tamponade, Tension PTX, Toxins, Thrombosis-PE, Thrombosis-MI).', '+', ARRAY['CS01','BK04'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0293', 'S5.3', 3, 'single_choice', 'NB tỉnh sau gây mê, đột ngột co giật toàn thân. Bước đầu tiên?', '["Trói NB", "Bảo vệ đầu/cột sống cổ + tư thế nghiêng an toàn (sau khi hết cơn) + oxy + hút đường thở + ECG/SpO2 + báo BS + chuẩn bị midazolam/diazepam", "Tiêm thuốc ngay", "Đứng nhìn"]'::jsonb, 1, 'Cơn co giật chu mổ: ưu tiên an toàn (không bị thương) + oxygenate + tìm nguyên nhân (LA toxicity, hạ Na, đột quỵ, awareness...) + thuốc nếu kéo dài.', '+', ARRAY['CS01','CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0294', 'S6.3', 3, 'single_choice', 'Audit hồ sơ phát hiện 30% ĐD ghi sai/thiếu chỉ số đau trong 24h sau mổ. Hành động cải tiến (PDCA) hợp lý:', '["Trừng phạt 30% đó", "Plan: phân tích nguyên nhân (thiếu kiến thức? thiếu thời gian? thiếu công cụ?) - Do: đào tạo + thiết kế lại form/template - Check: audit lại sau 1 tháng - Act: chuẩn hoá nếu cải thiện, điều chỉnh nếu chưa", "Bỏ qua", "Họp khiển trách"]'::jsonb, 1, 'PDCA (Plan-Do-Check-Act) - cải tiến chất lượng dựa trên dữ liệu + đào tạo + hệ thống.', '', ARRAY['BK01','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;

-- Variety: Mixed quick Lv 1-2 to round out (12 more questions)
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0295', 'S2.4', 1, 'single_choice', 'Định danh NB chuẩn theo Joint Commission cần ít nhất:', '["1 yếu tố (tên)", "2 yếu tố định danh: họ tên đầy đủ + ngày sinh / mã NB - KHÔNG dùng số phòng/giường", "3 yếu tố", "Số phòng giường là đủ"]'::jsonb, 1, '2 yếu tố định danh là tiêu chuẩn an toàn quốc tế.', '', ARRAY['BK01','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0296', 'S2.4', 2, 'single_choice', 'Sự cố y khoa (medical error) là gì?', '["Lỗi cố ý", "Bất kỳ thất bại nào trong quá trình chăm sóc (lập kế hoạch hoặc thực hiện) - bao gồm cả ''near miss'' (gần sai) - cần báo cáo không trừng phạt", "Chỉ lỗi gây tử vong", "Chỉ lỗi của BS"]'::jsonb, 1, 'Định nghĩa rộng - bao gồm near-miss - văn hoá báo cáo không trừng phạt giúp học tập + cải tiến.', '', ARRAY['BK01','VB10'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0297', 'S1.1', 1, 'single_choice', 'Phẩm chất cốt lõi của ĐD theo chuẩn năng lực BYT:', '["Y đức + chuyên môn + giao tiếp + làm việc nhóm + học suốt đời", "Chỉ chuyên môn", "Chỉ y đức", "Chỉ kinh nghiệm"]'::jsonb, 0, '5 nhóm năng lực cốt lõi của ĐD theo chuẩn năng lực BYT.', '', ARRAY['VB05','VB02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0298', 'S1.2', 2, 'single_choice', 'Phạm vi hành nghề (Scope of Practice) của ĐD trong khoa GMHS được quy định bởi:', '["Bộ luật Hình sự", "TT 32/2023/TT-BYT + chứng chỉ hành nghề + phân công nội bộ + năng lực được xác nhận", "Hợp đồng lao động", "Trưởng khoa quy định"]'::jsonb, 1, 'Phạm vi hành nghề ĐD theo TT 32/2023 + chứng chỉ + phân công + năng lực.', '', ARRAY['VB01','VB02'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0299', 'S3.1', 2, 'single_choice', 'Đánh giá block sau gây tê tủy sống dùng phương pháp:', '["Đo HA", "Pinprick test (kim châm nhẹ) đánh giá mất cảm giác đau + lạnh ấm + Bromage scale đánh giá block vận động", "Hỏi NB", "Chỉ quan sát"]'::jsonb, 1, 'Đánh giá block đầy đủ: cảm giác (pinprick, thermal) + vận động (Bromage) + thời gian khởi phát.', '*', ARRAY['BK03','KT04'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0300', 'S3.2', 2, 'single_choice', 'NB đang gây tê ngoài màng cứng để giảm đau chuyển dạ, đột ngột HA tụt + thai chậm nhịp. Xử trí?', '["Tiếp tục bơm thuốc", "Nghiêng trái + bù dịch + ephedrine/phenylephrine + báo BS + chuẩn bị mổ cấp cứu nếu cần (CTG vẫn xấu)", "Ngồi NB dậy", "Cho oxy đơn thuần"]'::jsonb, 1, 'Tụt HA do gây tê + suy thai = cấp cứu - xử trí ngay nguyên nhân tụ máu (aortocaval compression) + bù tuần hoàn.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0301', 'S5.3', 1, 'single_choice', 'Aldrete score ≥ 9/10 + sinh hiệu ổn là tiêu chí:', '["Vào phòng mổ", "Xuất PACU về khoa thường", "Cho ăn", "Tiêm thuốc"]'::jsonb, 1, 'Aldrete ≥ 9 + sinh hiệu ổn = đủ điều kiện rời PACU.', '+', ARRAY['CS07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0302', 'S3.8', 2, 'single_choice', 'Khi đặt NKQ thất bại (cannot intubate), bước tiếp theo theo Difficult Airway Algorithm:', '["Tiếp tục cố đặt", "Đảm bảo thông khí (Ambu/LMA) - cannot intubate, can ventilate vẫn tiếp tục oxy hoá, gọi hỗ trợ", "Bỏ NB", "Sốc điện"]'::jsonb, 1, 'CICV (Cannot Intubate, Cannot Ventilate) là cấp cứu tối khẩn - mở khí quản. CICV ≠ CICO. Cannot intubate can ventilate vẫn an toàn.', '*', ARRAY['BK03'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0303', 'S4.3', 2, 'single_choice', 'Đồ vải đã sử dụng trong phòng mổ được phân loại?', '["Đồ vải thường", "Đồ vải nhiễm khuẩn - đóng bao có ký hiệu, chuyển giặt tiệt khuẩn riêng - không trộn với đồ vải sạch", "Đem giặt tại nhà", "Vứt bỏ"]'::jsonb, 1, 'KSNK: đồ vải nhiễm khuẩn xử lý riêng + đóng bao + giặt nhiệt độ cao + tiệt khuẩn nếu cần.', '', ARRAY['CS02','VB07'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0304', 'S6.1', 1, 'single_choice', 'Chẩn đoán điều dưỡng (Nursing Diagnosis) khác chẩn đoán y khoa ở điểm:', '["Không khác", "Chẩn đoán ĐD tập trung vào phản ứng của NB với bệnh + nhu cầu chăm sóc (e.g. ''nguy cơ chảy máu'') chứ không phải bản thân bệnh (e.g. ''viêm phổi'')", "Chẩn đoán ĐD đơn giản hơn", "Không cần dùng"]'::jsonb, 1, 'Nursing diagnosis (NANDA) khác medical diagnosis - tập trung vào phản ứng + nhu cầu chăm sóc.', '', ARRAY['CS06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0305', 'S6.2', 1, 'single_choice', 'Khi ghi y lệnh miệng (verbal order) trong cấp cứu, ĐD ghi cụm từ chuẩn nào?', '["VO (Verbal Order) + tên BS ra y lệnh + nội dung + ngày giờ - BS ký xác nhận sau", "Tự ghi", "Không cần ghi", "Chỉ ghi tên thuốc"]'::jsonb, 0, 'VO/Verbal Order phải ghi rõ + tên BS + thời gian + BS ký xác nhận trong 24h theo quy định.', '', ARRAY['VB10','CS06'], 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id, skill_id, difficulty, type, question, options, correct_index, explanation, tt32_tag, source_doc_ids, status) VALUES ('Q0306', 'S4.2', 1, 'single_choice', 'Khu vực phòng mổ được chia thành 3 vùng theo mức độ vô khuẩn:', '["Sạch hạn chế (semi-restricted) + Vô khuẩn (restricted) + Không hạn chế (unrestricted)", "Vô khuẩn + bẩn", "Không phân chia", "Theo màu sắc"]'::jsonb, 0, 'Phân vùng 3 mức + luồng đi 1 chiều - chuẩn KSNK phòng mổ.', '', ARRAY['CS02','VB07'], 'approved') ON CONFLICT (id) DO NOTHING;

-- ============================================
-- END OF v2 SEED (Total: ~156 new questions)
-- ============================================
